spring:
  application:
    name: notify
  datasource:
    url: jdbc:postgresql://localhost:5432/notify_app
    username: postgres
    password: ahsan
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  secret:
    key: verysecurekeyevenisraelcantbreakithahahahaha
